### ISSUE TITLE
Demo app appears to crash when attempting to run in simulator

### ISSUE THREAD

**Issue by share9** [lludo/SwiftSunburstDiagram#1]
And doesn't appear to run in the live preview
<img width="1608" alt="Screen Shot 2019-06-29 at 12 50 23 PM" src="https://user-images.githubusercontent.com/37937142/60387692-95177a00-9a6c-11e9-9f96-f0f9c12b1444.png">

**Comment by lludo** [comment]
Are you using the beta 2?

**Comment by share9** [comment]
yes

**Comment by lludo** [comment]
That is weird, so it builds fine but crashes on run? I just tried and it worked fine in the simulator and device for me. I also just added sample data for the live preview.

**Comment by share9** [comment]
now it runs after I force quit Xcode beta 2 and reopened

**Comment by lludo** [comment]
Great! Xcode 11 is still in beta and is not always working well, especially with live previews in my experience.
